name: Build and test emulation

on: [push, pull_request, workflow_dispatch]

jobs:
  call-build:
    uses: ./.github/workflows/build-module.yml
    with:
      module: 'emulation'
    secrets: inherit
