name: Build and test roundtrips

on: [push, pull_request, workflow_dispatch, push]

jobs:
  call-build:
    uses: ./.github/workflows/build-module.yml
    with:
      module: 'roundtrips'
    secrets: inherit